# Generated by Django 4.0.5 on 2022-06-03 10:53

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customprofile_birth_date_customprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
