# Generated by Django 4.0.5 on 2022-06-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=None, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('S', 'BEING DELIVERED'), ('R', 'RECEIVED'), ('P', 'BEING PREPARED')], default=None, max_length=1)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='profiles.address')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('custom_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customprofile')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_adress', to='profiles.address')),
            ],
        ),
    ]
