# Generated by Django 4.0.5 on 2022-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('R', 'RECEIVED'), ('S', 'BEING DELIVERED')], default=None, max_length=1),
        ),
    ]
