# Generated by Django 4.0.5 on 2022-07-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_custom_profile_and_more'),
        ('books', '0005_alter_book_genre'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='profiles.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'RECEIVED'), ('P', 'BEING PREPARED'), ('S', 'BEING DELIVERED')], default=None, max_length=1),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book_cover', models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1)),
                ('book_language', models.CharField(choices=[('E', 'ENGLISH'), ('P', 'POLISH')], default=None, max_length=1)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
