# Generated by Django 4.0.5 on 2022-07-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_address_address_type_and_more'),
        ('orders', '0005_remove_order_book_alter_order_custom_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to='profiles.customprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('R', 'RECEIVED'), ('S', 'BEING DELIVERED')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('P', 'POLISH'), ('E', 'ENGLISH')], default=None, max_length=1),
        ),
    ]
