# Generated by Django 4.0.5 on 2022-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_active_alter_order_custom_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'BEING DELIVERED'), ('R', 'RECEIVED'), ('P', 'BEING PREPARED')], default=None, max_length=1),
        ),
    ]
