# Generated by Django 4.0.5 on 2022-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'BEING DELIVERED'), ('P', 'BEING PREPARED'), ('R', 'RECEIVED')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], default=None, max_length=1),
        ),
    ]
