# Generated by Django 4.0.5 on 2022-08-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_alter_orderitem_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'BEING DELIVERED'), ('R', 'RECEIVED'), ('P', 'BEING PREPARED')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1),
        ),
    ]
