# Generated by Django 4.0.5 on 2022-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status_alter_orderitem_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('R', 'RECEIVED'), ('S', 'BEING DELIVERED')], default=None, max_length=1),
        ),
    ]
