# Generated by Django 4.0.5 on 2022-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_genre'),
        ('orders', '0012_remove_orderitem_book_orderitem_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'RECEIVED'), ('P', 'BEING PREPARED'), ('S', 'BEING DELIVERED')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ManyToManyField(related_name='book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1),
        ),
    ]
