# Generated by Django 4.0.5 on 2022-08-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_genre'),
        ('orders', '0013_alter_order_status_alter_orderitem_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], default=None, max_length=1),
        ),
    ]
