# Generated by Django 4.0.5 on 2022-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderitem_book_orderitem_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S', 'BEING DELIVERED'), ('R', 'RECEIVED'), ('P', 'BEING PREPARED')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('P', 'POLISH'), ('E', 'ENGLISH')], default=None, max_length=1),
        ),
    ]
