# Generated by Django 4.0.5 on 2022-08-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_genre'),
        ('orders', '0015_alter_order_status_alter_orderitem_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'RECEIVED'), ('P', 'BEING PREPARED'), ('S', 'BEING DELIVERED')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('E', 'ENGLISH'), ('P', 'POLISH')], default=None, max_length=1),
        ),
    ]
