# Generated by Django 4.0.5 on 2022-08-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_address_address_type'),
        ('orders', '0016_alter_order_status_alter_orderitem_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.customprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('R', 'RECEIVED'), ('S', 'BEING DELIVERED')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1),
        ),
    ]
