# Generated by Django 4.0.5 on 2022-08-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_orderitem_custom_profile_alter_order_custom_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_profile',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_profile',
        ),
        migrations.AddField(
            model_name='order',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('S', 'BEING DELIVERED'), ('R', 'RECEIVED')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('P', 'POLISH'), ('E', 'ENGLISH')], default=None, max_length=1),
        ),
    ]
