# Generated by Django 4.0.5 on 2022-08-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_custom_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('E', 'ENGLISH'), ('P', 'POLISH')], default=None, max_length=1),
        ),
    ]
