# Generated by Django 4.0.5 on 2022-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'BEING PREPARED'), ('D', 'SENT'), ('R', 'RECEIVED')], default=None, max_length=1, null=True),
        ),
    ]
