# Generated by Django 4.0.5 on 2022-09-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book_cover',
            field=models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book_language',
            field=models.CharField(choices=[('E', 'ENGLISH'), ('P', 'POLISH')], max_length=1),
        ),
    ]
