# Generated by Django 4.0.5 on 2022-06-15 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('pages_number', models.PositiveIntegerField(null=True)),
                ('publishment_year', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=600)),
                ('genre', models.CharField(choices=[('FAN', 'Fantasy'), ('THR', 'Thriller'), ('SCF', 'Science-fiction'), ('HIS', 'Historical'), ('HOR', 'Horror')], max_length=3)),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
