# Generated by Django 4.0.5 on 2022-06-03 15:37

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=70)),
                ('pages_number', models.IntegerField(default=None)),
                ('publishment_year', models.IntegerField(default=None)),
                ('description', models.CharField(default=None, max_length=600)),
                ('image', versatileimagefield.fields.VersatileImageField(default=None, upload_to='')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
    ]
