# Generated by Django 4.0.5 on 2022-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HOR', 'Horror'), ('THR', 'Thriller'), ('HIS', 'Historical'), ('FAN', 'Fantasy'), ('SCF', 'Science-fiction')], max_length=3),
        ),
    ]
