# Generated by Django 4.0.5 on 2022-06-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HIS', 'Historical'), ('HOR', 'Horror'), ('SCF', 'Science-fiction'), ('FAN', 'Fantasy'), ('THR', 'Thriller')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishment_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
    ]
