# Generated by Django 4.0.5 on 2022-06-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_book_discount_percentage_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HIS', 'Historical'), ('HOR', 'Horror'), ('SCF', 'Science-fiction'), ('THR', 'Thriller'), ('FAN', 'Fantasy')], default=None, max_length=3, null=True),
        ),
    ]
