# Generated by Django 4.0.5 on 2022-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FAN', 'Fantasy'), ('THR', 'Thriller'), ('HOR', 'Horror'), ('HIS', 'Historical'), ('SCF', 'Science-fiction')], max_length=3),
        ),
    ]
