# Generated by Django 4.0.5 on 2022-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FAN', 'Fantasy'), ('SCF', 'Science-fiction'), ('THR', 'Thriller'), ('HIS', 'Historical'), ('HOR', 'Horror')], max_length=3),
        ),
    ]
