# Generated by Django 4.0.5 on 2022-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SCF', 'Science-fiction'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('HIS', 'Historical'), ('HOR', 'Horror')], default=None, max_length=3, null=True),
        ),
    ]
