# Generated by Django 4.0.5 on 2022-06-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('THR', 'Thriller'), ('HIS', 'Historical'), ('SCF', 'Science-fiction'), ('FAN', 'Fantasy'), ('HOR', 'Horror')], default=None, max_length=3, null=True),
        ),
    ]
