# Generated by Django 4.0.5 on 2022-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SCF', 'Science-fiction'), ('HOR', 'Horror'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('HIS', 'Historical')], max_length=3),
        ),
    ]
