# Generated by Django 4.0.5 on 2022-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('THR', 'Thriller'), ('FAN', 'Fantasy'), ('SCF', 'Science-fiction'), ('HIS', 'Historical'), ('HOR', 'Horror')], max_length=3),
        ),
    ]
