# Generated by Django 4.0.5 on 2022-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HIS', 'Historical'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('HOR', 'Horror'), ('SCF', 'Science-fiction')], max_length=3),
        ),
    ]
