# Generated by Django 4.0.5 on 2022-08-06 19:46

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_description_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FAN', 'Fantasy'), ('THR', 'Thriller'), ('HOR', 'Horror'), ('SCF', 'Science-fiction'), ('HIS', 'Historical')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to=''),
        ),
    ]
