# Generated by Django 4.0.5 on 2022-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FAN', 'Fantasy'), ('HIS', 'Historical'), ('THR', 'Thriller'), ('SCF', 'Science-fiction'), ('HOR', 'Horror')], default=None, max_length=3, null=True),
        ),
    ]
