# Generated by Django 4.0.5 on 2022-06-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HOR', 'Horror'), ('SCF', 'Science-fiction'), ('THR', 'Thriller'), ('FAN', 'Fantasy'), ('HIS', 'Historical')], default=None, max_length=3, null=True),
        ),
    ]
