# Generated by Django 4.0.5 on 2022-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_genre_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HOR', 'Horror'), ('HIS', 'Historical'), ('FAN', 'Fantasy'), ('SCF', 'Science-fiction'), ('THR', 'Thriller')], max_length=3, null=True),
        ),
    ]
