# Generated by Django 4.0.5 on 2022-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HIS', 'Historical'), ('SCF', 'Science-fiction'), ('THR', 'Thriller'), ('FAN', 'Fantasy'), ('HOR', 'Horror')], max_length=3, null=True),
        ),
    ]
