# Generated by Django 4.0.5 on 2022-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SCF', 'Science-fiction'), ('FAN', 'Fantasy'), ('HIS', 'Historical'), ('HOR', 'Horror'), ('THR', 'Thriller')], max_length=3, null=True),
        ),
    ]
