# Generated by Django 4.0.5 on 2022-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('HOR', 'Horror'), ('HIS', 'Historical'), ('FAN', 'Fantasy'), ('THR', 'Thriller'), ('SCF', 'Science-fiction')], max_length=3, null=True),
        ),
    ]
