# Generated by Django 4.0.5 on 2022-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SCF', 'Science-fiction'), ('HOR', 'Horror'), ('THR', 'Thriller'), ('HIS', 'Historical'), ('FAN', 'Fantasy')], max_length=3),
        ),
    ]
