# Generated by Django 4.0.5 on 2022-09-18 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_description_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
