# Generated by Django 4.0.5 on 2022-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
    ]
