# Generated by Django 4.0.5 on 2022-07-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_custom_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='custom_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customprofile'),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
    ]
