# Generated by Django 4.0.5 on 2022-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True),
        ),
    ]
