# Generated by Django 4.0.5 on 2022-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
    ]
