# Generated by Django 4.0.5 on 2022-09-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_address_default_alter_customprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='default_use',
        ),
    ]
